version: "3.3"

services:
  web:
    build: .
    depends_on:
      - mongodb
    ports:
      - "4000:4000"
    volumes:
      - .:/opt/app
    networks:
      - burea

  mongodb:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongodata:/data/db
    networks:
      - burea

volumes:
  mongodata:

networks:
  burea: